pipeline:
  test:
    when:
      event: push
    image: clojure
    commands:
      - lein test

  build-blueshift:
    when:
      event: push
    image: clojure
    commands:
      - lein uberjar

  publish:
    when:
      branch: master
      event: push
    secrets: ["docker_username", "docker_password"]
    image: plugins/docker
    repo: uswitch/blueshift
    tags:
      - "${DRONE_COMMIT_SHA:0:8}"
